[package]
name = "rust_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.8"
imgui-sdl2 = "0.15.0"
sdl2 = ">=0.34, <0.36"
gl = "0.10.0"
imgui-opengl-renderer = "0.11.1"
